# Generated by Django 3.0.10 on 2020-12-16 01:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlateModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('short_desc', models.CharField(max_length=150)),
                ('last_use', models.DateField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MenuModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('date', models.DateField(unique=True)),
                ('status', models.IntegerField(choices=[(0, 'Planning the menu'), (1, 'Waiting for preferences'), (2, 'Dispatched to employes')], default=0)),
                ('announced', models.BooleanField(default=False)),
                ('plates', models.ManyToManyField(related_name='in_menus', to='meals.PlateModel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MealModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('customization', models.TextField(blank=True, null=True)),
                ('participated', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(limit_choices_to={'role': 'E'}, on_delete=django.db.models.deletion.PROTECT, related_name='meals', to=settings.AUTH_USER_MODEL)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meals', to='meals.MenuModel')),
                ('plate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meals', to='meals.PlateModel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
