# Generated by Django 3.0.10 on 2020-12-18 21:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealmodel',
            name='employee',
            field=models.ForeignKey(limit_choices_to={'role': 'E'}, on_delete=django.db.models.deletion.PROTECT, related_name='meals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mealmodel',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meals', to='meals.MenuModel'),
        ),
        migrations.AddField(
            model_name='mealmodel',
            name='plate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='meals', to='meals.PlateModel'),
        ),
    ]
